# Bioinformatics Project 1.1 (Coronavirus)

In [1]:
import pandas as pd
import numpy as np
from openbabel import pybel
from IPython.display import SVG
from rdkit import Chem
from rdkit.Chem import Descriptors, Draw
from rdkit.Chem.Draw import IPythonConsole
from chembl_webresource_client.new_client import new_client
IPythonConsole.ipython_useSVG = True

In [3]:
target = new_client.target
target_query = target.search('coronavirus')
targets = pd.DataFrame.from_dict(target_query)

In [4]:
targets

,cross_references,organism,pref_name,score,species_group_flag,target_chembl_id,target_components,target_type,tax_id
0,[],Coronavirus,Coronavirus,17.0,False,CHEMBL613732,[],ORGANISM,11119
1,[],Feline coronavirus,Feline coronavirus,14.0,False,CHEMBL612744,[],ORGANISM,12663
2,[],Murine coronavirus,Murine coronavirus,14.0,False,CHEMBL5209664,[],ORGANISM,694005
3,[],Canine coronavirus,Canine coronavirus,14.0,False,CHEMBL5291668,[],ORGANISM,11153
4,[],Bovine coronavirus,Bovine coronavirus,14.0,False,CHEMBL6066646,[],ORGANISM,11128
5,[],Human coronavirus 229E,Human coronavirus 229E,13.0,False,CHEMBL613837,[],ORGANISM,11137
6,[],Human coronavirus OC43,Human coronavirus OC43,13.0,False,CHEMBL5209665,[],ORGANISM,31631
7,[],unidentified human coronavirus,unidentified human coronavirus,13.0,False,CHEMBL6195448,[],ORGANISM,694448
8,[],Human coronavirus NL63,Human coronavirus NL63,13.0,False,CHEMBL6195756,[],ORGANISM,277944
9,[],Middle East respiratory syndrome-related coron...,Middle East respiratory syndrome-related coron...,9.0,False,CHEMBL4296578,[],ORGANISM,1335626
10,[],Severe acute respiratory syndrome-related coro...,Replicase polyprotein 1a,5.0,False,CHEMBL3927,"[{'accession': 'P0C6U8', 'component_descriptio...",SINGLE PROTEIN,694009
11,[],Severe acute respiratory syndrome-related coro...,Replicase polyprotein 1ab,4.0,False,CHEMBL5118,"[{'accession': 'P0C6X7', 'component_descriptio...",SINGLE PROTEIN,694009
12,[],Severe acute respiratory syndrome coronavirus 2,Replicase polyprotein 1ab,4.0,False,CHEMBL4523582,"[{'accession': 'P0DTD1', 'component_descriptio...",SINGLE PROTEIN,2697049
13,[],Severe acute respiratory syndrome coronavirus 2,Protein cereblon/Replicase polyprotein 1ab,4.0,False,CHEMBL6067603,"[{'accession': 'Q96SW2', 'component_descriptio...",PROTEIN-PROTEIN INTERACTION,2697049
14,[],Severe acute respiratory syndrome coronavirus 2,von Hippel-Lindau disease tumor suppressor-SAR...,4.0,False,CHEMBL6067604,"[{'accession': 'P40337', 'component_descriptio...",PROTEIN-PROTEIN INTERACTION,2697049

In [5]:
targets.columns

Index(['cross_references', 'organism', 'pref_name', 'score',
       'species_group_flag', 'target_chembl_id', 'target_components',
       'target_type', 'tax_id'],
      dtype='str')

In [10]:
selected_target = targets.target_chembl_id[5]
selected_target

'CHEMBL613837'

Retrieve only bioactivity data for Human coronavirus (CHEMBL613732) that are reported as pChEMBL values.

In [11]:
activity = new_client.activity
results = activity.filter(target_chembl_id=selected_target).filter(standard_type="IC50")

In [12]:
df = pd.DataFrame.from_dict(results)
df.shape

(85, 47)

In [13]:
df.head()

,action_type,activity_comment,activity_id,activity_properties,assay_chembl_id,assay_description,assay_type,assay_variant_accession,assay_variant_mutation,bao_endpoint,...,target_organism,target_pref_name,target_tax_id,text_value,toid,type,units,uo_units,upper_value,value
0,None,None,22804102,"[{'comments': None, 'relation': '=', 'result_f...",CHEMBL4712028,Antiviral activity against HCoV-229E infected ...,F,None,None,BAO_0000190,...,Human coronavirus 229E,Human coronavirus 229E,11137,NaN,None,IC50,uM,UO_0000065,None,1.7
1,None,None,24984054,"[{'comments': None, 'relation': '<=', 'result_...",CHEMBL5227023,Antiviral activity against recombinant HCoV-22...,F,None,None,BAO_0000190,...,Human coronavirus 229E,Human coronavirus 229E,11137,NaN,None,IC50,uM,UO_0000065,None,0.7
2,None,None,24992649,[],CHEMBL5230448,Antiviral activity against HCoV-229E,F,None,None,BAO_0000190,...,Human coronavirus 229E,Human coronavirus 229E,11137,NaN,None,IC50,uM,UO_0000065,None,3.35
3,None,None,24992650,[],CHEMBL5230448,Antiviral activity against HCoV-229E,F,None,None,BAO_0000190,...,Human coronavirus 229E,Human coronavirus 229E,11137,NaN,None,IC50,nM,UO_0000065,None,1.48
4,None,None,24992680,"[{'comments': None, 'relation': '=', 'result_f...",CHEMBL5230463,Antiviral activity against HCoV-229E assessed ...,F,None,None,BAO_0000190,...,Human coronavirus 229E,Human coronavirus 229E,11137,NaN,None,IC50,uM,UO_0000065,None,5.1